# Navigation Links
#   To link a homepage section, specify the URL as a hash `#` followed by the section id.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 10

  - name: Publications
    url: '#publications'
    weight: 20

  - name: Working Papers
    url: '#wip'
    weight: 30

  - name: Research Grants
    url: '#projects2'
    weight: 35

  - name: Teaching
    url: '#courses'
    weight: 40

  - name: Contact
    url: '#contact'
    weight: 50
