# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/

###########################
# Appearance
###########################

theme: my_theme
day_night: true
font: 'native'
font_size: M

###########################
# SEO
###########################

site_type: Person
description: ''
twitter: ''

###########################
# Contact Information
###########################

email: oyhy@hku.hk
phone: (+852) 3917 4221
address:
  street: KKL Building Room 1321
  city: Pok Fo Lam
  region: Hong Kong
  country: Hong Kong
coordinates:
  latitude: '22.2835'
  longitude: '114.1391'

###########################
# Site Header
###########################

main_menu:
  enable: true
  align: l
  show_logo: true
  show_day_night: true

###########################
# Site Features
###########################

highlight: true
highlight_languages:
  - r
math: true
reading_time: true
abstract_length: 135
sharing: true

###########################
# Publications & Projects
###########################

publications:
  date_format: January 2006
  citation_style: mla
projects:
  post_view: 2

###########################
# Comments
###########################

comments:
  provider: ''

###########################
# Search
###########################

search:
  provider: wowchemy

###########################
# Marketing
###########################

marketing:
  google_analytics: ''
