name = "Academic CV"
license = "MIT"
licenselink = "https://github.com/wowchemy/starter-hugo-academic/blob/master/LICENSE.md"
description = "Build a professional academic résumé or personal website with ease. Fully customizable with 50+ widgets, multilingual support, and a research publication system."
homepage = "https://github.com/HugoBlox/theme-academic-cv"
demosite = "https://wowchemy.com/templates/"
min_version = "0.84"
tags = [
    "academic",
    "resume",
    "portfolio",
    "research",
    "publications",
    "responsive",
    "clean",
    "minimal",
    "landing page",
    "projects",
    "blog",
    "contact form",
    "gallery",
    "modern",
    "customizable",
    "technical"
]
features = [
    "page builder",
    "widgets",
    "research publication system",
    "filterable portfolio",
    "talks",
    "events",
    "slides",
    "gallery",
    "contact form",
    "multilingual support",
    "blog",
    "create courses",
    "dark mode",
    "light mode"
]

[author]
  name = "Geo Cushen"
  homepage = "https://geocushen.com"

# If porting an existing theme
[original]
  name = "Wowchemy Academic Starter"
  homepage = "https://github.com/wowchemy/starter-hugo-academic/"
  repo = "https://github.com/wowchemy/starter-hugo-academic"
